GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '760329' WITH GRANT OPTION;
FLUSH PRIVILEGES;
SET NAMES 'utf8mb4';

CREATE DATABASE IF NOT EXISTS TEST_DB;

SHOW WARNINGS;

CREATE TABLE user_tb (
  user_idx INT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(255),
  pw VARCHAR(255),
  user_name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255),
  gender INT DEFAULT 0,
  provider VARCHAR(255) DEFAULT 'local',
  sns_id VARCHAR(255),
  device_token VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  UNIQUE(user_id)
);

CREATE TABLE iot_tb (
  iot_idx INT AUTO_INCREMENT PRIMARY KEY,
  iot_id VARCHAR(255) UNIQUE NOT NULL,
  user_idx INT UNIQUE,
  iot_name VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  FOREIGN KEY (user_idx) REFERENCES user_tb(user_idx)
);

CREATE TABLE subscribe_tb (
  subscribe_idx INT AUTO_INCREMENT PRIMARY KEY,
  user_idx INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expired_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP + INTERVAL 1 MONTH),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_idx) REFERENCES user_tb(user_idx)
);

CREATE TABLE inquiry_tb (
  inquiry_idx INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255) NOT NULL,
  contents VARCHAR(255) NOT NULL,
  user_idx INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  FOREIGN KEY (user_idx) REFERENCES user_tb(user_idx)
);

CREATE TABLE iot_log_tb (
  id INT AUTO_INCREMENT PRIMARY KEY,
  iot_id VARCHAR(255) NOT NULL,
  log TEXT NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  FOREIGN KEY (iot_id) REFERENCES iot_tb(iot_id)
);

CREATE TABLE iot_sensor_tb (
  id INT AUTO_INCREMENT PRIMARY KEY,
  iot_id VARCHAR(255) NOT NULL,
  measured_weight INT NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  status BOOLEAN NOT NULL,
  FOREIGN KEY (iot_id) REFERENCES iot_tb(iot_id)
);
