name: Build and Tag and Push Docker Images
on:
  push:
    branches:
      - main
jobs:
  build-and-push-mysql-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_ID}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - name: Build and push MySQL image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/mysql:${{github.sha}}
          context: ./mysql
          file: ./mysql/Dockerfile

  build-and-push-python-image:
    needs: build-and-push-mysql-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_ID}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - name: Build and push Python image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/python:${{github.sha}}
          context: ./python
          file: ./python/Dockerfile
